language = "ts"
title = "Readma"
author = "elcoosp"
githubUsername = "elcoosp"
repoName = "readma"
xHandle = "elcoosp"
domain = "gmail"
email = "elcoosp"
backToTop = false

[images]
screenshot = "images/screenshot.gif"
logo = "images/logo.png"

[sections]
projectDescription = "Beautiful effortless README generator"
about = "Create README that rocks"
installation = "```sh\ndeno install readma\n```"
acknowledgments = "\n- [Best Readme](https://github.com/othneildrew/Best-README-Template)\n- [Table of content library](https://github.com/a-ahandani/ah-toc)"
gettingStarted = "See screenshot"
roadmap = "\n- [ ] CLI with config file\n- [ ] Auto defaults from known files like Cargo.toml/{deno,package}.json"
usage = "See `scripts/gen-readme.ts`"

[template]
bugReport = "bug-report--from-readme"
featRequest = "feature-request---from-readme"
