name: CI

on:
  push:
    branches: '**'
  pull_request:
    types: [opened, synchronize]
jobs:
  ci:
    uses: elcoosp/elcoosp-configs/.github/workflows/ci.yml@feat/deno-ci
    secrets: inherit
    with:
      deno-enabled: true
