# TODO: use https://jsr.io/@deno/bump-workspaces
name: ci

on: [push, pull_request]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Conventional commits check
        uses: oknozor/cocogitto-action@v3
  deno:
    name: check
    runs-on: ubuntu-latest
    env:
      DENO_DIR: deno_cache
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test @readma/core
        working-directory: core
        run: deno task t

      - name: Test @readma/cli
        working-directory: cli
        run: deno task t
