name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  ci:
    uses: elcoosp/elcoosp-configs/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      deno-enabled: true
