# TODO: use https://jsr.io/@deno/bump-workspaces
name: pub

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "**" # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  publish:
    name: publish-on-tag
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish on tag @readma/core
        working-directory: core
        run: deno publish

      # - name: Publish on tag @readma/cli
      #   working-directory: cli
      #   run: deno publish
