name: vbump
on: workflow_dispatch

jobs:
  build:
    name: Version bump
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2

      - name: Run workspaces version bump
        run: |
          git fetch --unshallow origin
          deno run -A jsr:@deno/bump-workspaces@0.1.21/cli
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GIT_USER_NAME: ${{ github.actor }}
          GIT_USER_EMAIL: ${{ github.actor }}@users.noreply.github.com
      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true
          git-user: ${{ github.actor }}
          git-user-email: ${{ github.actor }}@users.noreply.github.com
